#define WND_MAIN         1000
#define WND_CANVAS       1001
#define WND_TEXT         1002
#define WND_START        1003
#define WND_END          1004
#define WND_DESC         1005
#define WND_LISTBOX      1006

#define MI_NOT_IMPORTANT 1100

#define MI_BASE          1200
#define MI_SUN           MI_BASE+0
#define MI_MON           MI_BASE+1
#define MI_TUE           MI_BASE+2
#define MI_WED           MI_BASE+3
#define MI_THU           MI_BASE+4
#define MI_FRI           MI_BASE+5
#define MI_SAT           MI_BASE+6

#define MI_ADD           1300
#define MI_DEL           1301
#define MI_QUIT          1302
