#include <somobj.idl>

interface Dog : SOMObject
{
    attribute string name;

    void display();

    #ifdef __SOMIDL__
    implementation
    {
       releaseorder : display, 
                      _get_name, _set_name;
       dllname = "domestic.dll";
    };
    #endif
};
