#include <somobj.idl>

interface Employee: SOMObject
{
  attribute string name;

  #ifdef __SOMIDL__
  implementation
  {
    releaseorder : _get_name, _set_name;

    name:      noset;
    somInit:   override;
    somUninit: override;
  };
  #endif
};
